Feature/descw 2739 environment class
bcgov/naad-connector pull request #31
Opened 2024-11-21 23:49 UTC by robrien-bcgov

This is an incremental PR.

I plan to implement the rest of the ticket in a future PR, also to be merged into the DESCW-2739-Incremental branch.

- ([DESCW-2739](https://citz-gdx.atlassian.net/browse/DESCW-2739))
  - refactor entrypoint.sh to remove passing environment variables
  - refactor start.php to access environment variables using the NaadVars class.
  - refactor Dockerfile to remove environment variable declarations
  - add scripts to composer.json for starting the client and building the image.

2024-11-22 16:59 UTC, mhaswell-bcgov requested changes

2024-11-22 16:59 UTC, mhaswell-bcgov commented on src/NaadVars.php
> + */
```suggestion
 * @link     https://alerts.pelmorex.com/
 * @property-read string $naadName The instance of NAAD the application is connecting to, eg. NAAD-1, NAAD-2.
 */
```
If we add these phpdoc comments for each property then they'll show up in intellisense.

2024-11-22 16:59 UTC, mhaswell-bcgov commented on src/NaadVars.php
> +        'logFilePath'  => '/var/www/html/naad-socket.log',
```suggestion
        'logFilePath'  => 'naad-socket.log',
```
This whole env variable is going to be refactored away eventually anyway but for now this should be the default because otherwise I get this error when running start.php locally: `Fatal error: Uncaught UnexpectedValueException: There is no existing directory at "/var/www/html" and it could not be created: Permission denied`

2024-11-25 22:22 UTC, robrien-bcgov commented on src/NaadVars.php
> + */
done

2024-11-25 22:23 UTC, robrien-bcgov commented on src/NaadVars.php
> +                $this->$property = getenv($envKey);
done

2024-11-25 22:23 UTC, robrien-bcgov commented on src/NaadVars.php
> +                $this->$property = $this::$defaultValues[$property];
done

2024-11-26 16:16 UTC, mhaswell-bcgov approved these changes
Looks good!

2024-11-26 16:33 UTC, merged