Feature/descw 2765
bcgov/naad-connector pull request #35
Opened 2024-11-28 01:07 UTC by kshapka-bcgov

2024-11-28 15:56 UTC, robrien-bcgov approved these changes

2024-11-28 18:14 UTC, mhaswell-bcgov requested changes

2024-11-28 18:14 UTC, mhaswell-bcgov commented on src/NaadSocketClient.php
> +            }
The way I was thinking about DestinationClient working was something like this:
1. It receives an instance of the Database class so it can perform its own alert updates.
2. Whenever the SocketClient inserts new alert(s), it calls a function of DestinationClient that doesn't take any arguments.
3. That function (`sendAlerts()` or something) selects any unsent alerts from the database (which should include the alert(s) that were just inserted by SocketClient) and attempts to send them all.
4. DestinationClient then updates each alert using the Database (updateAlert() function which doesn't exist yet).

This way the SocketClient doesn't care what happens to the alert once it's inserted, the DestinationClient is solely responsible for that part of the process. 
I think the code is all written correctly so we'd just need to move it around.

2024-12-03 16:09 UTC, kshapka-bcgov commented on src/Entity/Alert.php
> +        return $this->success ?? false;
Yes, but this causes issues for entries which were inserted into the database before these changes. This accomplishes the same thing while being backwards compatible.

2024-12-06 18:33 UTC, mhaswell-bcgov approved these changes

2024-12-06 19:39 UTC, merged