DESCW-2771 replace curl with guzzle client
bcgov/naad-connector pull request #37
Opened 2024-12-02 21:43 UTC by robrien-bcgov

4 commits squashed using `git rebase -i HEAD~4`

- still needs cleanups and finishing touches. DESCW-2771 adds guzzle instead of CURL for grabbing the alerts from the naad repo
- some minor refactoring as well, for easy maintenance descw-2771 fix typo
descw-2771 slightly refactor the socket client to fix failing tests

2024-12-02 22:18 UTC, mhaswell-bcgov commented on src/NaadSocketClient.php
> +    protected function validateResponse(?string $response): bool|SimpleXMLElement
Why is this change needed?

2024-12-02 22:19 UTC, robrien-bcgov commented on src/NaadSocketClient.php
> +    protected function validateResponse(?string $response): bool|SimpleXMLElement
the tests fail on this method because they send a null instead of a string.

that's why i changed the type hinting to allow a null to be sent

2024-12-02 22:28 UTC, robrien-bcgov commented on src/NaadSocketClient.php
> +    protected function validateResponse(?string $response): bool|SimpleXMLElement
look at this - it's failing because the method expects a string, not null

It only happens on this branch
![image](https://github.com/user-attachments/assets/189f50b7-01bd-4f60-a7da-dd651ce93a23)

2024-12-02 23:06 UTC, mhaswell-bcgov requested changes

2024-12-02 23:06 UTC, mhaswell-bcgov commented on src/NaadRepositoryClient.php
> +    public function fetchAlert(array $reference): ?string
```suggestion
    public function fetchAlert(string $reference): ?string
```
It's still a string at this point isn't it?

2024-12-02 23:06 UTC, mhaswell-bcgov commented on src/NaadRepositoryClient.php
> +            return null;
Can we have this throw the Exception instead of returning null so we don't have to change the SocketClient::validateAlert() arguments?

2024-12-02 23:28 UTC, robrien-bcgov commented on src/NaadRepositoryClient.php
> +        $date = strtok($reference['sent'], 'T');
yeah the url will be me3ssed up, teh request will fail in the try/catch block, and fetchAlert will return null

2024-12-03 00:06 UTC, robrien-bcgov commented on src/NaadRepositoryClient.php
> +        $date = strtok($reference['sent'], 'T');
or in this case, it will throw an error

2024-12-03 00:28 UTC, mhaswell-bcgov approved these changes

2024-12-03 22:53 UTC, mhaswell-bcgov approved these changes

2024-12-03 22:56 UTC, merged