descw-2792 add .dockerignore
bcgov/naad-connector pull request #39
Opened 2024-12-04 23:20 UTC by robrien-bcgov

2024-12-04 23:33 UTC, ShawnTurple commented on Dockerfile
> +# Install dependencies and PHP extensions
in future, only the acceptance criteria, if you think the dockerfile needs to be cleaned up, then it should be discussed, and a ticket created, otherwise it makes a simple pr into one that we have to understand what you actually did, and if it has any impact,

2024-12-05 00:15 UTC, mhaswell-bcgov requested changes

2024-12-05 00:15 UTC, mhaswell-bcgov commented on .dockerignore
> +docker-compose.yaml
```suggestion
docker-compose.yaml
.devcontainer
.DS_Store
.env
.github
.gitignore
.phpunit.cache
.phpunit.result.cache
```
I think we could exclude even a few more although you might not have some of these files so they wouldn't show up for you.
![image](https://github.com/user-attachments/assets/0401ea29-b3a4-46b2-ba6f-a5e55d5168ab)

2024-12-05 16:20 UTC, mhaswell-bcgov approved these changes

2024-12-05 16:21 UTC, merged